general:
  lr2: 0.01
  wd2: 0.0001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Computers:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.000001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Cora:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
PubMed:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
CiteSeer:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Photo:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Cornell:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Wisconsin:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Texas:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Chameleon:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Squirrel:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
Actor:
  learning_rate: 0.0001
  output_dim: 256
  num_proj_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.1
  tau: 0.5
  num_epochs: 1000
  weight_decay: 0
  lr2: 0.01
  wd2: 0.00001
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
pretrain:
  struct:
    k_eigs: 32
    subgraph_type: "rwr"         # random walk with restart
    walk_length: 64              # reduced from 256 for faster sampling
    restart_prob: 0.8            # probability of restarting at the origin node
    num_subgraphs: 128           # reduced from 1024 for faster epochs  
    batch_size: 32               # reduced from 256 for memory efficiency
    epochs: 50                   # reduced from 200 for quicker testing
    lr: 1e-3
    output_dim: 256
    num_proj_dim: 256
    activation: 'relu'
    gnn_type: 'GAT'
    num_layers: 2
    tau: 0.5
    learning_rate: 0.001
    weight_decay: 0
    num_epochs: 50

  grace:
    # Existing GRACE configs inherit from dataset-specific blocks
    output_dim: 256
    num_proj_dim: 256

transfer:
  hidden_dim: 64
  output_dim: 256
  activation: 'relu'
  gnn_type: 'GAT'
  num_layers: 2
  learning_rate: 0.001
  weight_decay: 0
  epoch: 0
  epoch1: 100
  epoch2: 10000
  decay_epoch: 1000
  b1: 0.5
  b2: 0.999
  batch_size: 128
  lambda_cyc: 15
  lambda_anc: 5
  lambda_cos: 0
  lambda_dis: 5
  lambda_str: 0
  lambda_map: 5
  lambda_id: 5
  checkpoint_interval: 10
  lr2: 0.01
  wd2: 0.000001

